name: Build and Release Android APK

on:
  push:
    tags:
      - v*  # Trigger only when pushing tags like v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use Eclipse Temurin JDK
          java-version: '17'

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/debug/app-debug.apk"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "New APK build automatically generated."
          token: ${{ secrets.GITHUB_TOKEN }}
